# Code Generated from [__init__.py.gotmpl], DO NOT EDIT.

CONNECTING = "connecting.png"
GREEN_NEXT_BUTTON = "green_next_button.png"
HOME_BUTTON = "home_button.png"
LIMITED_SALE_OPEN = "limited_sale_open.png"
RACE_CHOOSE_ITEM = "race_choose_item.png"
RACE_ITEM_PARFAIT = "race_item_parfait.png"
RETRY_BUTTON = "retry_button.png"
RP_NOT_ENOUGH = "rp_not_enough.png"
TEAM_RACE_BUTTON = "team_race_button.png"
TEAM_RACE_CHOOSE_COMPETITOR = "team_race_choose_competitor.png"
TEAM_RACE_GUARANTEED_WIN_REWARD = "team_race_guaranteed_win_reward.png"
TEAM_RACE_LOSE = "team_race_lose.png"
TEAM_RACE_NEXT_BUTTON = "team_race_next_button.png"
TEAM_RACE_SEE_RESULT_BUTTON = "team_race_see_result_button.png"
TEAM_RACE_START_BUTTON = "team_race_start_button.png"
TEAM_RACE_WIN = "team_race_win.png"
