# Code Generated from [__init__.py.gotmpl], DO NOT EDIT.
ANY_POS = "any.pos.png"
CANCEL_BUTTON = "cancel_button.png"
CHAMPIONS_MEETING_CONFIRM_TITLE = "champions_meeting_confirm_title.png"
CHAMPIONS_MEETING_ENTRY_BUTTON = "champions_meeting_entry_button.png"
CHAMPIONS_MEETING_ENTRY_BUTTON_DISABLED = "champions_meeting_entry_button_disabled.png"
CHAMPIONS_MEETING_RACE_BUTTON = "champions_meeting_race_button.png"
CHAMPIONS_MEETING_RACE_BUTTON_POS = "champions_meeting_race_button.pos.png"
CHAMPIONS_MEETING_REGISTER_BUTTON = "champions_meeting_register_button.png"
CHAMPIONS_MEETING_REWARD_BUTTON = "champions_meeting_reward_button.png"
CHAMPIONS_MEETING_REWARD_BUTTON_POS = "champions_meeting_reward_button.pos.png"
CHAMPIONS_MEETING_USING_TICKET = "champions_meeting_using_ticket.png"
CHAMPIONS_MEETING_USING_TICKET_POS = "champions_meeting_using_ticket.pos.png"
CLOSE_BUTTON = "close_button.png"
CLOSE_NOW_BUTTON = "close_now_button.png"
CLOSE_NOW_BUTTON_POS = "close_now_button.pos.png"
CONNECTING = "connecting.png"
CONNECTING_POS = "connecting.pos.png"
DAILY_RACE = "daily_race.png"
DAILY_RACE_HARD = "daily_race_hard.png"
DAILY_RACE_TICKET_NOT_ENOUGH = "daily_race_ticket_not_enough.png"
EXCHANGE_BUTTON = "exchange_button.png"
EXCHANGE_CONFIRM_BUTTON = "exchange_confirm_button.png"
EXCHANGE_CONFIRM_BUTTON_POS = "exchange_confirm_button.pos.png"
GO_HOME_BUTTON = "go_home_button.png"
GO_HOME_BUTTON_POS = "go_home_button.pos.png"
GO_TO_LIMITED_SALE = "go_to_limited_sale.png"
GO_TO_RACE_BUTTON = "go_to_race_button.png"
GREEN_BATTLE_BUTTON = "green_battle_button.png"
GREEN_NEXT_BUTTON = "green_next_button.png"
GREEN_OK_BUTTON = "green_ok_button.png"
GREEN_TIGHT_OK_BUTTON = "green_tight_ok_button.png"
HOME_BUTTON = "home_button.png"
JUPITER_CUP = "jupiter_cup.png"
JUPITER_CUP_POS = "jupiter_cup.pos.png"
LEGEND_RACE_COLLECT_ALL_REWARD = "legend_race_collect_all_reward.png"
LEGEND_RACE_COLLECT_ALL_REWARD_POS = "legend_race_collect_all_reward.pos.png"
LEGEND_RACE_CONFIRM_BUTTON = "legend_race_confirm_button.png"
LEGEND_RACE_CONFIRM_BUTTON_POS = "legend_race_confirm_button.pos.png"
LEGEND_RACE_RACE_BUTTON = "legend_race_race_button.png"
LEGEND_RACE_RACE_BUTTON_POS = "legend_race_race_button.pos.png"
LEGEND_RACE_REWARD = "legend_race_reward.png"
LEGEND_RACE_REWARD_POS = "legend_race_reward.pos.png"
LEGEND_RACE_START_BUTTON = "legend_race_start_button.png"
LEGEND_RACE_START_BUTTON_POS = "legend_race_start_button.pos.png"
LIMITED_SALE_OPEN = "limited_sale_open.png"
MOONLIGHT_PRIZE = "moonlight_prize.png"
MOONLIGHT_PRIZE_POS = "moonlight_prize.pos.png"
PREDICTION_CIRCLE_OUTLINE = "prediction_circle_outline.png"
PREDICTION_DOUBLE_CIRCLE = "prediction_double_circle.png"
PREDICTION_TRIANGLE_OUTLINE = "prediction_triangle_outline.png"
RACE_AGAIN_BUTTON = "race_again_button.png"
RACE_BUTTON = "race_button.png"
RACE_CHOOSE_ITEM = "race_choose_item.png"
RACE_CONFIRM_BUTTON = "race_confirm_button.png"
RACE_ITEM_PARFAIT = "race_item_parfait.png"
RACE_RESULT_BUTTON = "race_result_button.png"
RACE_RESULT_FAIL_POS = "race_result_fail.pos.png"
RACE_RESULT_NO1 = "race_result_no1.png"
RACE_RESULT_NO10 = "race_result_no10.png"
RACE_RESULT_NO2 = "race_result_no2.png"
RACE_RESULT_NO3 = "race_result_no3.png"
RACE_RESULT_NO4 = "race_result_no4.png"
RACE_RESULT_NO5 = "race_result_no5.png"
RACE_RESULT_NO6 = "race_result_no6.png"
RACE_RESULT_NO8 = "race_result_no8.png"
RACE_RUNNING_STYLE_CHANGE_BUTTON = "race_running_style_change_button.png"
RACE_RUNNING_STYLE_CHANGE_BUTTON_POS = "race_running_style_change_button.pos.png"
RACE_START_BUTTON = "race_start_button.png"
RETRY_BUTTON = "retry_button.png"
RETURN_BUTTON = "return_button.png"
ROULETTE_DERBY_BINGO = "roulette_derby_bingo.png"
ROULETTE_DERBY_BINGO_POS = "roulette_derby_bingo.pos.png"
ROULETTE_DERBY_GET = "roulette_derby_get.png"
ROULETTE_DERBY_GET_POS = "roulette_derby_get.pos.png"
ROULETTE_DERBY_REWARD_TEXT = "roulette_derby_reward_text.png"
ROULETTE_DERBY_SKIP_BUTTON = "roulette_derby_skip_button.png"
ROULETTE_DERBY_TAP_BUTTON = "roulette_derby_tap_button.png"
ROULETTE_DERBY_TAP_BUTTON_POS = "roulette_derby_tap_button.pos.png"
ROULETTE_DERBY_TAP_BUTTON_DISABLED = "roulette_derby_tap_button_disabled.png"
ROULETTE_DERBY_TAP_BUTTON_DISABLED_POS = "roulette_derby_tap_button_disabled.pos.png"
RP_NOT_ENOUGH = "rp_not_enough.png"
SCROLL_TO_END = "scroll_to_end.png"
SCROLL_TO_END_POS = "scroll_to_end.pos.png"
SINGLE_MODE_AOHARU_AUTO_FORMATION_TITLE = "single_mode_aoharu_auto_formation_title.png"
SINGLE_MODE_AOHARU_AUTO_FORMATION_TITLE_POS = (
    "single_mode_aoharu_auto_formation_title.pos.png"
)
SINGLE_MODE_AOHARU_BATTLE_CONFIRM_TITLE = "single_mode_aoharu_battle_confirm_title.png"
SINGLE_MODE_AOHARU_BATTLE_CONFIRM_TITLE_POS = (
    "single_mode_aoharu_battle_confirm_title.pos.png"
)
SINGLE_MODE_AOHARU_CHOOSE_COMPETITOR = "single_mode_aoharu_choose_competitor.png"
SINGLE_MODE_AOHARU_CHOOSE_COMPETITOR_POS = (
    "single_mode_aoharu_choose_competitor.pos.png"
)
SINGLE_MODE_AOHARU_CLASS_DETAIL_BUTTON = "single_mode_aoharu_class_detail_button.png"
SINGLE_MODE_AOHARU_CLASS_DETAIL_BUTTON_POS = (
    "single_mode_aoharu_class_detail_button.pos.png"
)
SINGLE_MODE_AOHARU_FINAL_BANNER = "single_mode_aoharu_final_banner.png"
SINGLE_MODE_AOHARU_FINAL_BATTLE_BUTTON = "single_mode_aoharu_final_battle_button.png"
SINGLE_MODE_AOHARU_FINAL_BATTLE_BUTTON_POS = (
    "single_mode_aoharu_final_battle_button.pos.png"
)
SINGLE_MODE_AOHARU_FORMAL_RACE_BANNER = "single_mode_aoharu_formal_race_banner.png"
SINGLE_MODE_AOHARU_FORMAL_RACE_BANNER_POS = (
    "single_mode_aoharu_formal_race_banner.pos.png"
)
SINGLE_MODE_AOHARU_MAIN_RACE_BUTTON = "single_mode_aoharu_main_race_button.png"
SINGLE_MODE_AOHARU_MAIN_RACE_BUTTON_POS = "single_mode_aoharu_main_race_button.pos.png"
SINGLE_MODE_AOHARU_RACE_RESULT_BUTTON = "single_mode_aoharu_race_result_button.png"
SINGLE_MODE_AOHARU_RACE_RESULT_BUTTON_POS = (
    "single_mode_aoharu_race_result_button.pos.png"
)
SINGLE_MODE_AOHARU_SOUL_FULL = "single_mode_aoharu_soul_full.png"
SINGLE_MODE_CHARACTER_DETAIL_BUTTON = "single_mode_character_detail_button.png"
SINGLE_MODE_CHARACTER_DETAIL_BUTTON_POS = "single_mode_character_detail_button.pos.png"
SINGLE_MODE_CHARACTER_DETAIL_TITLE = "single_mode_character_detail_title.png"
SINGLE_MODE_CHARACTER_DETAIL_TITLE_POS = "single_mode_character_detail_title.pos.png"
SINGLE_MODE_CLASS_DETAIL_BUTTON = "single_mode_class_detail_button.png"
SINGLE_MODE_CLASS_DETAIL_BUTTON_POS = "single_mode_class_detail_button.pos.png"
SINGLE_MODE_CLASS_DETAIL_TITLE = "single_mode_class_detail_title.png"
SINGLE_MODE_CLASS_DETAIL_TITLE_POS = "single_mode_class_detail_title.pos.png"
SINGLE_MODE_COMMAND_GO_OUT = "single_mode_command_go_out.png"
SINGLE_MODE_COMMAND_GO_OUT_POS = "single_mode_command_go_out.pos.png"
SINGLE_MODE_COMMAND_HEALTH_CARE = "single_mode_command_health_care.png"
SINGLE_MODE_COMMAND_HEALTH_CARE_POS = "single_mode_command_health_care.pos.png"
SINGLE_MODE_COMMAND_RACE = "single_mode_command_race.png"
SINGLE_MODE_COMMAND_RACE_POS = "single_mode_command_race.pos.png"
SINGLE_MODE_COMMAND_SUMMER_REST = "single_mode_command_summer_rest.png"
SINGLE_MODE_COMMAND_SUMMER_REST_POS = "single_mode_command_summer_rest.pos.png"
SINGLE_MODE_COMMAND_TRAINING = "single_mode_command_training.png"
SINGLE_MODE_COMMAND_TRAINING_POS = "single_mode_command_training.pos.png"
SINGLE_MODE_CONDITION_HEADACHE = "single_mode_condition_headache.png"
SINGLE_MODE_CONDITION_OVERWEIGHT = "single_mode_condition_overweight.png"
SINGLE_MODE_CONTINUE = "single_mode_continue.png"
SINGLE_MODE_CONTINUE_POS = "single_mode_continue.pos.png"
SINGLE_MODE_CONTINUOUS_RACE_TITLE = "single_mode_continuous_race_title.png"
SINGLE_MODE_CRANE_GAME_BUTTON = "single_mode_crane_game_button.png"
SINGLE_MODE_CRANE_GAME_BUTTON_POS = "single_mode_crane_game_button.pos.png"
SINGLE_MODE_CRANE_GAME_PLAY_GUIDE_BUTTON = (
    "single_mode_crane_game_play_guide_button.png"
)
SINGLE_MODE_CRANE_GAME_PLAY_GUIDE_BUTTON_POS = (
    "single_mode_crane_game_play_guide_button.pos.png"
)
SINGLE_MODE_END_BUTTON = "single_mode_end_button.png"
SINGLE_MODE_END_BUTTON_POS = "single_mode_end_button.pos.png"
SINGLE_MODE_FANS_NOT_ENOUGH = "single_mode_fans_not_enough.png"
SINGLE_MODE_FANS_NOT_ENOUGH_POS = "single_mode_fans_not_enough.pos.png"
SINGLE_MODE_FINISH = "single_mode_finish.png"
SINGLE_MODE_FINISH_POS = "single_mode_finish.pos.png"
SINGLE_MODE_FINISH_BUTTON = "single_mode_finish_button.png"
SINGLE_MODE_FINISH_BUTTON_POS = "single_mode_finish_button.pos.png"
SINGLE_MODE_FORMAL_RACE_BANNER = "single_mode_formal_race_banner.png"
SINGLE_MODE_FORMAL_RACE_BANNER_POS = "single_mode_formal_race_banner.pos.png"
SINGLE_MODE_GENE_INHERIT = "single_mode_gene_inherit.png"
SINGLE_MODE_GO_OUT_FRIEND_ICON = "single_mode_go_out_friend_icon.png"
SINGLE_MODE_GO_OUT_FRIEND_ICON_POS = "single_mode_go_out_friend_icon.pos.png"
SINGLE_MODE_GO_OUT_MENU_TITLE = "single_mode_go_out_menu_title.png"
SINGLE_MODE_GO_OUT_MENU_TITLE_POS = "single_mode_go_out_menu_title.pos.png"
SINGLE_MODE_GO_OUT_OPTION_LEFT_BORDER = "single_mode_go_out_option_left_border.png"
SINGLE_MODE_GO_TO_SCHEDULED_RACE_BUTTON = "single_mode_go_to_scheduled_race_button.png"
SINGLE_MODE_GO_TO_SCHEDULED_RACE_BUTTON_POS = (
    "single_mode_go_to_scheduled_race_button.pos.png"
)
SINGLE_MODE_GOOD_RACE_ADAPTABILITY_STAR = "single_mode_good_race_adaptability_star.png"
SINGLE_MODE_LIVE_BUTTON = "single_mode_live_button.png"
SINGLE_MODE_OPTION1 = "single_mode_option1.png"
SINGLE_MODE_OPTION1_POS = "single_mode_option1.pos.png"
SINGLE_MODE_OPTION2 = "single_mode_option2.png"
SINGLE_MODE_OPTION2_POS = "single_mode_option2.pos.png"
SINGLE_MODE_OPTION3 = "single_mode_option3.png"
SINGLE_MODE_OPTION3_POS = "single_mode_option3.pos.png"
SINGLE_MODE_OPTION4 = "single_mode_option4.png"
SINGLE_MODE_OPTION4_POS = "single_mode_option4.pos.png"
SINGLE_MODE_OPTION5 = "single_mode_option5.png"
SINGLE_MODE_OPTION5_POS = "single_mode_option5.pos.png"
SINGLE_MODE_RACE_DETAIL_BUTTON = "single_mode_race_detail_button.png"
SINGLE_MODE_RACE_DETAIL_BUTTON_POS = "single_mode_race_detail_button.pos.png"
SINGLE_MODE_RACE_DETAIL_NO1_FAN_COUNT = "single_mode_race_detail_no1_fan_count.png"
SINGLE_MODE_RACE_DETAIL_NO1_FAN_COUNT_POS = (
    "single_mode_race_detail_no1_fan_count.pos.png"
)
SINGLE_MODE_RACE_DETAIL_TITLE = "single_mode_race_detail_title.png"
SINGLE_MODE_RACE_DETAIL_TITLE_POS = "single_mode_race_detail_title.pos.png"
SINGLE_MODE_RACE_MENU_FAN_ICON = "single_mode_race_menu_fan_icon.png"
SINGLE_MODE_RACE_MENU_FAN_ICON_POS = "single_mode_race_menu_fan_icon.pos.png"
SINGLE_MODE_RACE_NEXT_BUTTON = "single_mode_race_next_button.png"
SINGLE_MODE_RACE_START_BUTTON = "single_mode_race_start_button.png"
SINGLE_MODE_REST = "single_mode_rest.png"
SINGLE_MODE_REST_POS = "single_mode_rest.pos.png"
SINGLE_MODE_SCHEDULED_RACE_OPENING = "single_mode_scheduled_race_opening.png"
SINGLE_MODE_SCHEDULED_RACE_OPENING_POS = "single_mode_scheduled_race_opening.pos.png"
SINGLE_MODE_SCHEDULED_RACE_OPENING_BANNER = (
    "single_mode_scheduled_race_opening_banner.png"
)
SINGLE_MODE_SCHEDULED_RACE_OPENING_BANNER_POS = (
    "single_mode_scheduled_race_opening_banner.pos.png"
)
SINGLE_MODE_TARGET_RACE_NO_PERMISSION = "single_mode_target_race_no_permission.png"
SINGLE_MODE_TARGET_RACE_NO_PERMISSION_POS = (
    "single_mode_target_race_no_permission.pos.png"
)
SINGLE_MODE_TARGET_UNFINISHED = "single_mode_target_unfinished.png"
SINGLE_MODE_TARGET_UNFINISHED_POS = "single_mode_target_unfinished.pos.png"
SINGLE_MODE_TRAINING_CONFIRM = "single_mode_training_confirm.png"
SINGLE_MODE_TRAINING_CONFIRM_POS = "single_mode_training_confirm.pos.png"
SINGLE_MODE_URA_FINALS = "single_mode_ura_finals.png"
SINGLE_MODE_URA_FINALS_POS = "single_mode_ura_finals.pos.png"
SKIP_BUTTON = "skip_button.png"
SKIP_BUTTON_POS = "skip_button.pos.png"
TEAM_RACE_BUTTON = "team_race_button.png"
TEAM_RACE_CHOOSE_COMPETITOR = "team_race_choose_competitor.png"
TEAM_RACE_CHOOSE_COMPETITOR_POS = "team_race_choose_competitor.pos.png"
TEAM_RACE_DRAW = "team_race_draw.png"
TEAM_RACE_HIGH_SCORE_UPDATED = "team_race_high_score_updated.png"
TEAM_RACE_LOSE = "team_race_lose.png"
TEAM_RACE_NEXT_BUTTON = "team_race_next_button.png"
TEAM_RACE_RESULT_BUTTON = "team_race_result_button.png"
TEAM_RACE_WIN = "team_race_win.png"
