# -*- coding=UTF-8 -*-
# This typing file was generated by typing_from_help.py
"""
win32ui - A module, encapsulating the Microsoft Foundation Classes.
"""

from ._pywin32 import *
from typing import *

class error(Exception):
    """
    Common base class for all non-exit exceptions.
    """

    __weakref__: ...
    """
    list of weak references to the object (if defined)
    """

    ...

def AddToRecentFileList(*args, **kwargs):
    """ """
    ...

def ComparePath(*args, **kwargs):
    """ """
    ...

def CreateBitmap() -> PyCBitmap:
    """Creates a bitmap object."""
    ...

def CreateBitmapFromHandle(*args, **kwargs):
    """ """
    ...

def CreateBrush(*args, **kwargs):
    """ """
    ...

def CreateButton(*args, **kwargs):
    """ """
    ...

def CreateColorDialog(*args, **kwargs):
    """ """
    ...

def CreateControl(*args, **kwargs):
    """ """
    ...

def CreateControlBar(*args, **kwargs):
    """ """
    ...

def CreateCtrlView(*args, **kwargs):
    """ """
    ...

def CreateDC(*args, **kwargs):
    """ """
    ...

def CreateDCFromHandle(dc_handle: int) -> PyCDC:
    """ """
    ...

def CreateDebuggerThread(*args, **kwargs):
    """ """
    ...

def CreateDialog(*args, **kwargs):
    """ """
    ...

def CreateDialogBar(*args, **kwargs):
    """ """
    ...

def CreateDialogIndirect(*args, **kwargs):
    """ """
    ...

def CreateDocTemplate(*args, **kwargs):
    """ """
    ...

def CreateEdit(*args, **kwargs):
    """ """
    ...

def CreateEditView(*args, **kwargs):
    """ """
    ...

def CreateFileDialog(*args, **kwargs):
    """ """
    ...

def CreateFont(*args, **kwargs):
    """ """
    ...

def CreateFontDialog(*args, **kwargs):
    """ """
    ...

def CreateFormView(*args, **kwargs):
    """ """
    ...

def CreateFrame(*args, **kwargs):
    """ """
    ...

def CreateImageList(*args, **kwargs):
    """ """
    ...

def CreateListCtrl(*args, **kwargs):
    """ """
    ...

def CreateListView(*args, **kwargs):
    """ """
    ...

def CreateMDIChild(*args, **kwargs):
    """ """
    ...

def CreateMDIFrame(*args, **kwargs):
    """ """
    ...

def CreateMenu(*args, **kwargs):
    """ """
    ...

def CreatePalette(*args, **kwargs):
    """ """
    ...

def CreatePen(*args, **kwargs):
    """ """
    ...

def CreatePopupMenu(*args, **kwargs):
    """ """
    ...

def CreatePrintDialog(*args, **kwargs):
    """ """
    ...

def CreateProgressCtrl(*args, **kwargs):
    """ """
    ...

def CreatePropertyPage(*args, **kwargs):
    """ """
    ...

def CreatePropertyPageIndirect(*args, **kwargs):
    """ """
    ...

def CreatePropertySheet(*args, **kwargs):
    """ """
    ...

def CreateRectRgn(*args, **kwargs):
    """ """
    ...

def CreateRgn(*args, **kwargs):
    """ """
    ...

def CreateRichEditCtrl(*args, **kwargs):
    """ """
    ...

def CreateRichEditDocTemplate(*args, **kwargs):
    """ """
    ...

def CreateRichEditView(*args, **kwargs):
    """ """
    ...

def CreateSliderCtrl(*args, **kwargs):
    """ """
    ...

def CreateSplitter(*args, **kwargs):
    """ """
    ...

def CreateStatusBar(*args, **kwargs):
    """ """
    ...

def CreateStatusBarCtrl(*args, **kwargs):
    """ """
    ...

def CreateThread(*args, **kwargs):
    """ """
    ...

def CreateToolBar(*args, **kwargs):
    """ """
    ...

def CreateToolBarCtrl(*args, **kwargs):
    """ """
    ...

def CreateToolTipCtrl(*args, **kwargs):
    """ """
    ...

def CreateTreeCtrl(*args, **kwargs):
    """ """
    ...

def CreateTreeView(*args, **kwargs):
    """ """
    ...

def CreateView(*args, **kwargs):
    """ """
    ...

def CreateWindowFromHandle(*args, **kwargs):
    """ """
    ...

def CreateWnd(*args, **kwargs):
    """ """
    ...

def DestroyDebuggerThread(*args, **kwargs):
    """ """
    ...

def DisplayTraceback(*args, **kwargs):
    """ """
    ...

def DoWaitCursor(*args, **kwargs):
    """ """
    ...

def Enable3dControls(*args, **kwargs):
    """ """
    ...

def EnableControlContainer(*args, **kwargs):
    """ """
    ...

def FindWindow(*args, **kwargs):
    """ """
    ...

def FindWindowEx(*args, **kwargs):
    """ """
    ...

def FullPath(*args, **kwargs):
    """ """
    ...

def GetActiveWindow(*args, **kwargs):
    """ """
    ...

def GetApp(*args, **kwargs):
    """ """
    ...

def GetAppName(*args, **kwargs):
    """ """
    ...

def GetAppRegistryKey(*args, **kwargs):
    """ """
    ...

def GetBytes(*args, **kwargs):
    """ """
    ...

def GetCommandLine(*args, **kwargs):
    """ """
    ...

def GetDeviceCaps(*args, **kwargs):
    """ """
    ...

def GetFileTitle(*args, **kwargs):
    """ """
    ...

def GetFocus(*args, **kwargs):
    """ """
    ...

def GetForegroundWindow(*args, **kwargs):
    """ """
    ...

def GetHalftoneBrush(*args, **kwargs):
    """ """
    ...

def GetInitialStateRequest(*args, **kwargs):
    """ """
    ...

def GetMainFrame(*args, **kwargs):
    """ """
    ...

def GetName(*args, **kwargs):
    """ """
    ...

def GetProfileFileName(*args, **kwargs):
    """ """
    ...

def GetProfileVal(*args, **kwargs):
    """ """
    ...

def GetRecentFileList(*args, **kwargs):
    """ """
    ...

def GetResource(*args, **kwargs):
    """ """
    ...

def GetThread(*args, **kwargs):
    """ """
    ...

def GetType(*args, **kwargs):
    """ """
    ...

def InitRichEdit(*args, **kwargs):
    """ """
    ...

def InstallCallbackCaller(*args, **kwargs):
    """ """
    ...

def IsDebug(*args, **kwargs):
    """ """
    ...

def IsObject(*args, **kwargs):
    """ """
    ...

def IsWin32s(*args, **kwargs):
    """ """
    ...

def LoadDialogResource(*args, **kwargs):
    """ """
    ...

def LoadLibrary(*args, **kwargs):
    """ """
    ...

def LoadMenu(*args, **kwargs):
    """ """
    ...

def LoadStdProfileSettings(*args, **kwargs):
    """ """
    ...

def LoadString(*args, **kwargs):
    """ """
    ...

def MessageBox(*args, **kwargs):
    """ """
    ...

def OutputDebug(*args, **kwargs):
    """ """
    ...

def OutputDebugString(*args, **kwargs):
    """ """
    ...

def PrintTraceback(*args, **kwargs):
    """ """
    ...

def PumpWaitingMessages(*args, **kwargs):
    """ """
    ...

def RegisterWndClass(*args, **kwargs):
    """ """
    ...

def RemoveRecentFile(*args, **kwargs):
    """ """
    ...

def SetAppHelpPath(*args, **kwargs):
    """ """
    ...

def SetAppName(*args, **kwargs):
    """ """
    ...

def SetCurrentInstanceHandle(*args, **kwargs):
    """ """
    ...

def SetCurrentResourceHandle(*args, **kwargs):
    """ """
    ...

def SetDialogBkColor(*args, **kwargs):
    """ """
    ...

def SetProfileFileName(*args, **kwargs):
    """ """
    ...

def SetRegistryKey(*args, **kwargs):
    """ """
    ...

def SetResource(*args, **kwargs):
    """ """
    ...

def SetStatusText(*args, **kwargs):
    """ """
    ...

def StartDebuggerPump(*args, **kwargs):
    """ """
    ...

def StopDebuggerPump(*args, **kwargs):
    """ """
    ...

def TranslateMessage(*args, **kwargs):
    """ """
    ...

def TranslateVirtualKey(*args, **kwargs):
    """ """
    ...

def WinHelp(*args, **kwargs):
    """ """
    ...

AFX_IDW_PANE_FIRST: int = 59648

AFX_IDW_PANE_LAST: int = 59903

AFX_WS_DEFAULT_VIEW: int = 1350565888

CDocTemplate_Confidence_maybeAttemptForeign: int = 1

CDocTemplate_Confidence_maybeAttemptNative: int = 2

CDocTemplate_Confidence_noAttempt: int = 0

CDocTemplate_Confidence_yesAlreadyOpen: int = 5

CDocTemplate_Confidence_yesAttemptForeign: int = 3

CDocTemplate_Confidence_yesAttemptNative: int = 4

CDocTemplate_docName: int = 1

CDocTemplate_fileNewName: int = 2

CDocTemplate_filterExt: int = 4

CDocTemplate_filterName: int = 3

CDocTemplate_regFileTypeId: int = 5

CDocTemplate_regFileTypeName: int = 6

CDocTemplate_windowTitle: int = 0

CRichEditView_WrapNone: int = 0

CRichEditView_WrapToTargetDevice: int = 2

CRichEditView_WrapToWindow: int = 1

FWS_ADDTOTITLE: int = 32768

FWS_PREFIXTITLE: int = 16384

FWS_SNAPTOBARS: int = 8192

IDB_BROWSER_HIER: int = 11145

IDB_DEBUGGER_HIER: int = 16018

IDB_HIERFOLDERS: int = 11142

IDC_ABOUT_VERSION: int = 15062

IDC_AUTOCOMPLETE: int = 15071

IDC_AUTO_RELOAD: int = 15059

IDC_BUTTON1: int = 15004

IDC_BUTTON2: int = 15005

IDC_BUTTON3: int = 15006

IDC_BUTTON4: int = 15068

IDC_CALLTIPS: int = 15072

IDC_CHECK1: int = 15066

IDC_CHECK2: int = 15067

IDC_CHECK3: int = 11151

IDC_COMBO1: int = 15058

IDC_COMBO2: int = 15076

IDC_DBG_ADD: int = 16004

IDC_DBG_BREAKPOINTS: int = 36889

IDC_DBG_CLEAR: int = 16006

IDC_DBG_CLOSE: int = 16010

IDC_DBG_GO: int = 15022

IDC_DBG_STACK: int = 36888

IDC_DBG_STEP: int = 16013

IDC_DBG_STEPOUT: int = 15020

IDC_DBG_STEPOVER: int = 15021

IDC_DBG_WATCH: int = 40002

IDC_EDIT1: int = 15008

IDC_EDIT2: int = 15009

IDC_EDIT3: int = 15010

IDC_EDIT4: int = 15011

IDC_EDITOR_COLOR: int = 15073

IDC_EDIT_TABS: int = 15028

IDC_FOLD_ENABLE: int = 15078

IDC_FOLD_ON_OPEN: int = 15073

IDC_FOLD_SHOW_LINES: int = 15070

IDC_INDENT_SIZE: int = 15055

IDC_KEYBOARD_CONFIG: int = 15074

IDC_LIST1: int = 15013

IDC_MARGIN_FOLD: int = 15082

IDC_MARGIN_LINENUMBER: int = 15081

IDC_MARGIN_MARKER: int = 15080

IDC_PROMPT1: int = 15014

IDC_PROMPT2: int = 15015

IDC_PROMPT3: int = 15016

IDC_PROMPT4: int = 15017

IDC_PROMPT_TABS: int = 15039

IDC_RADIO1: int = 15061

IDC_RADIO2: int = 15062

IDC_RIGHTEDGE_COLUMN: int = 15083

IDC_RIGHTEDGE_DEFINE: int = 15086

IDC_RIGHTEDGE_ENABLE: int = 15084

IDC_RIGHTEDGE_SAMPLE: int = 15085

IDC_SPIN1: int = 15056

IDC_SPIN2: int = 15057

IDC_SPIN3: int = 15060

IDC_TABTIMMY_BG: int = 15078

IDC_TABTIMMY_IND: int = 15079

IDC_TABTIMMY_NONE: int = 15077

IDC_TAB_SIZE: int = 15054

IDC_USE_SMART_TABS: int = 15064

IDC_USE_TABS: int = 15053

IDC_VIEW_EOL: int = 15071

IDC_VIEW_INDENTATIONGUIDES: int = 15072

IDC_VIEW_WHITESPACE: int = 15070

IDC_VSS_INTEGRATE: int = 15063

IDD_ABOUTBOX: int = 11139

IDD_DUMMYPROPPAGE: int = 11148

IDD_GENERAL_STATUS: int = 11149

IDD_LARGE_EDIT: int = 11147

IDD_PP_DEBUGGER: int = 16012

IDD_PP_EDITOR: int = 11153

IDD_PP_FORMAT: int = 15046

IDD_PP_IDE: int = 11155

IDD_PP_TABS: int = 11160

IDD_PP_TOOLMENU: int = 11156

IDD_PROPDEMO1: int = 15019

IDD_PROPDEMO2: int = 15018

IDD_RUN_SCRIPT: int = 15045

IDD_SET_TABSTOPS: int = 15041

IDD_SIMPLE_INPUT: int = 15044

IDD_TREE: int = 15043

IDD_TREE_MB: int = 15042

IDR_CNTR_INPLACE: int = 6

IDR_DEBUGGER: int = 11133

IDR_MAINFRAME: int = 11128

IDR_PYTHONCONTYPE: int = 11132

IDR_PYTHONTYPE: int = 11129

IDR_PYTHONTYPE_CNTR_IP: int = 11131

IDR_TEXTTYPE: int = 11130

ID_APP_ABOUT: int = 57664

ID_APP_EXIT: int = 57665

ID_EDIT_CLEAR: int = 57632

ID_EDIT_CLEAR_ALL: int = 57633

ID_EDIT_COPY: int = 57634

ID_EDIT_CUT: int = 57635

ID_EDIT_FIND: int = 57636

ID_EDIT_GOTO_LINE: int = 57638

ID_EDIT_PASTE: int = 57637

ID_EDIT_REDO: int = 57644

ID_EDIT_REPEAT: int = 57640

ID_EDIT_REPLACE: int = 57641

ID_EDIT_SELECT_ALL: int = 57642

ID_EDIT_SELECT_BLOCK: int = 36875

ID_EDIT_UNDO: int = 57643

ID_FILE_CHECK: int = 36881

ID_FILE_CLOSE: int = 57602

ID_FILE_IMPORT: int = 36867

ID_FILE_LOCATE: int = 36868

ID_FILE_MRU_FILE1: int = 57616

ID_FILE_MRU_FILE2: int = 57617

ID_FILE_MRU_FILE3: int = 57618

ID_FILE_MRU_FILE4: int = 57619

ID_FILE_NEW: int = 57600

ID_FILE_OPEN: int = 57601

ID_FILE_PAGE_SETUP: int = 57605

ID_FILE_PRINT: int = 57607

ID_FILE_PRINT_PREVIEW: int = 57609

ID_FILE_PRINT_SETUP: int = 57606

ID_FILE_RUN: int = 36864

ID_FILE_SAVE: int = 57603

ID_FILE_SAVE_ALL: int = 36882

ID_FILE_SAVE_AS: int = 57604

ID_HELP_GUI_REF: int = 36870

ID_HELP_OTHER: int = 14950

ID_HELP_PYTHON: int = 36872

ID_INDICATOR_COLNUM: int = 15038

ID_INDICATOR_LINENUM: int = 15040

ID_NEXT_PANE: int = 57680

ID_PREV_PANE: int = 57681

ID_SEPARATOR: int = 0

ID_VIEW_BROWSE: int = 36869

ID_VIEW_EOL: int = 36894

ID_VIEW_FIXED_FONT: int = 15031

ID_VIEW_FOLD_COLLAPSE: int = 36898

ID_VIEW_FOLD_COLLAPSE_ALL: int = 36897

ID_VIEW_FOLD_EXPAND: int = 36895

ID_VIEW_FOLD_EXPAND_ALL: int = 36896

ID_VIEW_FOLD_TOPLEVEL: int = 36900

ID_VIEW_INDENTATIONGUIDES: int = 36901

ID_VIEW_INTERACTIVE: int = 36873

ID_VIEW_OPTIONS: int = 36879

ID_VIEW_RIGHT_EDGE: int = 36904

ID_VIEW_STATUS_BAR: int = 59393

ID_VIEW_TOOLBAR: int = 59392

ID_VIEW_TOOLBAR_DBG: int = 59424

ID_VIEW_WHITESPACE: int = 36874

ID_WINDOW_ARRANGE: int = 57649

ID_WINDOW_CASCADE: int = 57650

ID_WINDOW_NEW: int = 57648

ID_WINDOW_SPLIT: int = 57653

ID_WINDOW_TILE_HORZ: int = 57651

ID_WINDOW_TILE_VERT: int = 57652

LM_COMMIT: int = 64

LM_HORZ: int = 2

LM_HORZDOCK: int = 8

LM_LENGTHY: int = 32

LM_MRUWIDTH: int = 4

LM_STRETCH: int = 1

LM_VERTDOCK: int = 16

MFS_4THICKFRAME: int = 512

MFS_BLOCKSYSMENU: int = 4096

MFS_MOVEFRAME: int = 2048

MFS_SYNCACTIVE: int = 256

MFS_THICKFRAME: int = 1024

PD_ALLPAGES: int = 0

PD_COLLATE: int = 16

PD_DISABLEPRINTTOFILE: int = 524288

PD_ENABLEPRINTHOOK: int = 4096

PD_ENABLEPRINTTEMPLATE: int = 16384

PD_ENABLEPRINTTEMPLATEHANDLE: int = 65536

PD_ENABLESETUPHOOK: int = 8192

PD_ENABLESETUPTEMPLATE: int = 32768

PD_ENABLESETUPTEMPLATEHANDLE: int = 131072

PD_HIDEPRINTTOFILE: int = 1048576

PD_NONETWORKBUTTON: int = 2097152

PD_NOPAGENUMS: int = 8

PD_NOSELECTION: int = 4

PD_NOWARNING: int = 128

PD_PAGENUMS: int = 2

PD_PRINTSETUP: int = 64

PD_PRINTTOFILE: int = 32

PD_RETURNDC: int = 256

PD_RETURNDEFAULT: int = 1024

PD_RETURNIC: int = 512

PD_SELECTION: int = 1

PD_SHOWHELP: int = 2048

PD_USEDEVMODECOPIES: int = 262144

PD_USEDEVMODECOPIESANDCOLLATE: int = 262144

PSWIZB_BACK: int = 1

PSWIZB_DISABLEDFINISH: int = 8

PSWIZB_FINISH: int = 4

PSWIZB_NEXT: int = 2

UNICODE: int = 1

__all__: ...
"""
['AFX_IDW_PANE_FIRST', 'AFX_IDW_PANE_LAST', 'AFX_WS_DEFAULT_...
"""

copyright: Text
"""
'Copyright 1994-2018 Mark Hammond'
"""

debug: int = 0

dllhandle: int = 1610547200

types: ...
"""
{'PyCBitmap': <class 'PyCBitmap'>, 'PyCBrush': <class 'PyCBrus...
"""
