# -*- coding=UTF-8 -*-
# This typing file was generated by typing_from_help.py
"""
win32process

"""

import typing

def AttachThreadInput(*args, **kwargs):
    """ """
    ...

def CreateProcess(*args, **kwargs):
    """ """
    ...

def CreateProcessAsUser(*args, **kwargs):
    """ """
    ...

def CreateRemoteThread(*args, **kwargs):
    """ """
    ...

def EnumProcessModules(*args, **kwargs):
    """ """
    ...

def EnumProcessModulesEx(*args, **kwargs):
    """ """
    ...

def EnumProcesses(*args, **kwargs):
    """ """
    ...

def ExitProcess(*args, **kwargs):
    """ """
    ...

def GetCurrentProcess(*args, **kwargs):
    """ """
    ...

def GetCurrentProcessId() -> int:
    """Retrieves the process identifier of the calling process."""
    ...

def GetExitCodeProcess(*args, **kwargs):
    """ """
    ...

def GetExitCodeThread(*args, **kwargs):
    """ """
    ...

def GetGuiResources(*args, **kwargs):
    """ """
    ...

def GetModuleFileNameEx(*args, **kwargs):
    """ """
    ...

def GetPriorityClass(*args, **kwargs):
    """ """
    ...

def GetProcessAffinityMask(*args, **kwargs):
    """ """
    ...

def GetProcessId(*args, **kwargs):
    """ """
    ...

def GetProcessIoCounters(*args, **kwargs):
    """ """
    ...

def GetProcessMemoryInfo(*args, **kwargs):
    """ """
    ...

def GetProcessPriorityBoost(*args, **kwargs):
    """ """
    ...

def GetProcessShutdownParameters(*args, **kwargs):
    """ """
    ...

def GetProcessTimes(*args, **kwargs):
    """ """
    ...

def GetProcessVersion(*args, **kwargs):
    """ """
    ...

def GetProcessWindowStation(*args, **kwargs):
    """ """
    ...

def GetProcessWorkingSetSize(*args, **kwargs):
    """ """
    ...

def GetStartupInfo(*args, **kwargs):
    """ """
    ...

def GetThreadIOPendingFlag(*args, **kwargs):
    """ """
    ...

def GetThreadPriority(*args, **kwargs):
    """ """
    ...

def GetThreadPriorityBoost(*args, **kwargs):
    """ """
    ...

def GetThreadTimes(*args, **kwargs):
    """ """
    ...

def GetWindowThreadProcessId(hwnd: int) -> typing.Tuple[int, int]:
    """
    Retrieves the identifier of the thread and process that created the specified window.
    """
    ...

def IsWow64Process(*args, **kwargs):
    """ """
    ...

def ReadProcessMemory(*args, **kwargs):
    """ """
    ...

def ResumeThread(*args, **kwargs):
    """ """
    ...

def STARTUPINFO(*args, **kwargs):
    """ """
    ...

def SetPriorityClass(*args, **kwargs):
    """ """
    ...

def SetProcessAffinityMask(*args, **kwargs):
    """ """
    ...

def SetProcessPriorityBoost(*args, **kwargs):
    """ """
    ...

def SetProcessShutdownParameters(*args, **kwargs):
    """ """
    ...

def SetProcessWorkingSetSize(*args, **kwargs):
    """ """
    ...

def SetThreadAffinityMask(*args, **kwargs):
    """ """
    ...

def SetThreadIdealProcessor(*args, **kwargs):
    """ """
    ...

def SetThreadPriority(*args, **kwargs):
    """ """
    ...

def SetThreadPriorityBoost(*args, **kwargs):
    """ """
    ...

def SuspendThread(*args, **kwargs):
    """ """
    ...

def TerminateProcess(*args, **kwargs):
    """ """
    ...

def VirtualAllocEx(*args, **kwargs):
    """ """
    ...

def VirtualFreeEx(*args, **kwargs):
    """ """
    ...

def WriteProcessMemory(*args, **kwargs):
    """ """
    ...

def beginthreadex(*args, **kwargs):
    """ """
    ...

ABOVE_NORMAL_PRIORITY_CLASS: int = 32768

BELOW_NORMAL_PRIORITY_CLASS: int = 16384

CREATE_BREAKAWAY_FROM_JOB: int = 16777216

CREATE_DEFAULT_ERROR_MODE: int = 67108864

CREATE_NEW_CONSOLE: int = 16

CREATE_NEW_PROCESS_GROUP: int = 512

CREATE_NO_WINDOW: int = 134217728

CREATE_PRESERVE_CODE_AUTHZ_LEVEL: int = 33554432

CREATE_SEPARATE_WOW_VDM: int = 2048

CREATE_SHARED_WOW_VDM: int = 4096

CREATE_SUSPENDED: int = 4

CREATE_UNICODE_ENVIRONMENT: int = 1024

DEBUG_ONLY_THIS_PROCESS: int = 2

DEBUG_PROCESS: int = 1

DETACHED_PROCESS: int = 8

HIGH_PRIORITY_CLASS: int = 128

IDLE_PRIORITY_CLASS: int = 64

LIST_MODULES_32BIT: int = 1

LIST_MODULES_64BIT: int = 2

LIST_MODULES_ALL: int = 3

LIST_MODULES_DEFAULT: int = 0

MAXIMUM_PROCESSORS: int = 64

NORMAL_PRIORITY_CLASS: int = 32

REALTIME_PRIORITY_CLASS: int = 256

STARTF_FORCEOFFFEEDBACK: int = 128

STARTF_FORCEONFEEDBACK: int = 64

STARTF_RUNFULLSCREEN: int = 32

STARTF_USECOUNTCHARS: int = 8

STARTF_USEFILLATTRIBUTE: int = 16

STARTF_USEPOSITION: int = 4

STARTF_USESHOWWINDOW: int = 1

STARTF_USESIZE: int = 2

STARTF_USESTDHANDLES: int = 256

THREAD_MODE_BACKGROUND_BEGIN: int = 65536

THREAD_MODE_BACKGROUND_END: int = 131072

THREAD_PRIORITY_ABOVE_NORMAL: int = 1

THREAD_PRIORITY_BELOW_NORMAL: int = -1

THREAD_PRIORITY_HIGHEST: int = 2

THREAD_PRIORITY_IDLE: int = -15

THREAD_PRIORITY_LOWEST: int = -2

THREAD_PRIORITY_NORMAL: int = 0

THREAD_PRIORITY_TIME_CRITICAL: int = 15

UNICODE: int = 1

__all__: ...
"""
['ABOVE_NORMAL_PRIORITY_CLASS', 'AttachThreadInput', 'BELOW_...
"""
