# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
# fmt: off
"""
version info.
"""

from __future__ import absolute_import, division, print_function, unicode_literals

from datetime import datetime

VERSION = "1.13.1"
RELEASE_DATE = datetime.fromtimestamp(1639591259)
LAST_GIT_COMMIT_DESCRIBE = "v1.13.0-2-g9c712ff"
LAST_GIT_COMMIT_HASH = "9c712ffd9c14d9305496e0ec7695eca0f53f67a6"
LAST_GIT_COMMIT_AUTHOR_NAME = "NateScarlet"
LAST_GIT_COMMIT_AUTHOR_EMAIL = "NateScarlet@Gmail.com"
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1639591246)
LAST_GIT_COMMIT_SUBJECT = "fix: should use plural file name for race results"
LAST_GIT_COMMIT_BODY = ""
