# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if ( Test-Path dev-requirements.txt ) { & pip install -r dev-requirements.txt }
        if ( Test-Path requirements.txt ) { & pip install -r requirements.txt }
    - name: Test
      run: |
        make test
    - name: Lint
      run: |
        make lint
